name: Build and Release

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  Build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install
        shell: bash

      - name: Build installer
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            npm run build:icon
            npm run build -- --publish=never
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            npm run build:icon:mac
            npm run build:mac -- --publish=never
          else
            npm run build:icon:linux
            npm run build:linux -- --publish=never
          fi
        shell: bash

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            dist/*.exe
            dist/*.dmg
            dist/*.AppImage
            dist/*.deb
